services:
  kafka:
    image: apache/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: "controller,broker"
      KAFKA_NODE_ID: 0
      KAFKA_CONTROLLER_QUORUM_VOTERS: "0@kafka:9093"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: "5L6g3nShT-eMCtK--X86sw"
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - max-efficiency-net

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - max-efficiency-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
    # NOTE: Указывание докеру что надо взять гпу (отрубить для сервака там её нет)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  ollama-setup:
    image: curlimages/curl:latest
    container_name: ollama-setup
    depends_on:
      ollama:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Pulling model...' &&
        curl -X POST http://ollama:11434/api/pull -d '{\"name\": \"qwen3:1.7b\"}' &&
        echo 'Model pulled successfully'
      "
    networks:
      - max-efficiency-net
    restart: "no"

  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: ai-service
    depends_on:
      kafka:
        condition: service_healthy
      ollama:
        condition: service_healthy
    volumes:
      - ./ai-service/config.yaml:/app/config.yaml:ro
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
      KAFKA_INPUT_TOPIC: ai-service
      KAFKA_OUTPUT_TOPIC: main-service
      KAFKA_GROUP_ID: max-efficiency
      SUMMARIZER_MODEL: qwen3:1.7b
      LOG_LEVEL: INFO
      OLLAMA_HOST: http://ollama:11434
    networks:
      - max-efficiency-net
    restart: unless-stopped
    deploy:
      replicas: 1

volumes:
  ollama-data:
  kafka_data:

networks:
  max-efficiency-net:
    driver: bridge
