### ===== USER TESTS =====
### Base URL
@baseUrl = http://localhost:8000/api/v1

### ===== DEBUG =====

### Получить всех пользователей (DEBUG)
GET {{baseUrl}}/users
Content-Type: application/json

### ===== CREATE =====

### Создать нового пользователя
POST {{baseUrl}}/users
Content-Type: application/json

{
  "max_user_id": 12345,
  "username": "test_user"
}

### Создать пользователя без username (опциональное поле)
POST {{baseUrl}}/users
Content-Type: application/json

{
  "max_user_id": 67890
}

### ===== GET =====

### Получить пользователя по max_user_id
GET {{baseUrl}}/users/12345
Content-Type: application/json

### Получить пользователя по несуществующему max_user_id (должна вернуться 404)
GET {{baseUrl}}/users/99999
Content-Type: application/json

### Получить все категории пользователя
GET {{baseUrl}}/users/user/1/categories
Content-Type: application/json

### Получить все теги пользователя
GET {{baseUrl}}/users/user/1/tags
Content-Type: application/json

### Получить все задачи пользователя
GET {{baseUrl}}/users/user/1/tasks
Content-Type: application/json

### ===== UPDATE =====

### Обновить данные пользователя
PATCH {{baseUrl}}/users/12345
Content-Type: application/json

{
  "username": "updated_user"
}

### Попытка обновить несуществующего пользователя (должна вернуться 404)
PATCH {{baseUrl}}/users/99999
Content-Type: application/json

{
  "username": "test"
}

